### ISSUE TITLE
ignore docker interface

### ISSUE THREAD

**Issue by ThorstenS-linux** [kenfallon/fix-ssh-on-pi#1]
https://github.com/kenfallon/fix-ssh-on-pi/blob/6e1da315686004235f9f078fa16b6422ec49393e/put-pi-in-ansible-host.bash#L38

Pleas also exclude docker in this egrep.

thanks
/thorsten

**Comment by kenfallon** [comment]
OK added some more as requested. 

There is probably a better way to find the active interface.

**Comment by kenfallon** [comment]
Pushed fix.
