### ISSUE TITLE
Put-pi-in-ansible-host doesn't recognize Raspberry Pi4s

### ISSUE THREAD

**Issue by dbblackdiamond** [kenfallon/fix-ssh-on-pi#12]
I have tried using the put-pi-in-ansible-host script to discover the raspberry pi in my network and it didn't recognize the Pi4s. The reason is that Pi4s MAC addresses start with e4:5f:01, so line 50 on the script needs to be changed to include that.

Change from:  _grep -iE 'b8:27:eb|dc:a6:32'_ to  _grep -iE 'b8:27:eb|dc:a6:32|e4:5f:01_'

**Comment by kenfallon** [comment]
Sorry that took so long.
