### ISSUE TITLE
Option to build images for rpis without eth0

### ISSUE THREAD

**Issue by danielo515** [kenfallon/fix-ssh-on-pi#3]
Hello.
This line seems to rely on the fact that the eth0 exists:

```
  echo "sed \"s/raspberrypi/\$( sed 's/://g' /sys/class/net/eth0/address )/g\" -i /etc/hostname /etc/hosts" >> "${sdcard_mount}/firstboot.sh"
```
But there are some models, like the rpizeroW that only have wlan. It will be cool if we can pass a variable or prompt a yes/no question abut using eth0 or the wireless interface, or maybe provide a custom algorithm to generate.

Thanks

**Comment by kenfallon** [comment]
Good point. I need to think about that.

**Comment by danielo515** [comment]
Thanks! I'll keep an eye on it

**Comment by kenfallon** [comment]
Finally got to fix this. Sorry it took so long. 

I moved it to firstboot.sh, based on the interfaces that are UP at a given time. It will use wired first before wifi. If there is none the name will not be changed.
