### ISSUE TITLE
is there a good way to install packages onto the image?

### ISSUE THREAD

**Issue by c650** [kenfallon/fix-ssh-on-pi#6]
hey there again,

I am wondering if there is a good way to install packages onto the image so that they are reading to go when the Pi boots up. In the past I have tried chrooting, but apt is funky in chroot. I have also tried downloading the debs, but that also seems like a lot. 

Have you come across any better way to do this?

**Comment by kenfallon** [comment]
This script was part of the miniseries "Manage your Raspberry Pi fleet with Ansible" which was covered on [opensource.com](https://opensource.com/article/20/9/raspberry-pi-ansible) and on [Hacker Public Radio](http://hackerpublicradio.org/eps.php?id=3173).

The goal is to produce a common base Raspberry Pi OS image that doesn't change often but, once it's installed, can automatically be customized, maintained, and managed remotely. 

So what you're suggesting is not what I would recommend.
