### ISSUE TITLE
python3 crypt not working under MacOS

### ISSUE THREAD

**Issue by tillhanke** [kenfallon/fix-ssh-on-pi#7]
Hi, I just found the repo and really like it. It is simple and looks quite clean. Sadly I found a little bug concerning MacOS:

The crypt module in python is sadly not cross platform compatible. This is explained in [this post](https://stackoverflow.com/questions/13052047/python-crypt-in-osx)
To get this repository working under MacOS it is instead possible to use passlib (as well explained in the post mentioned).

**Comment by kenfallon** [comment]
The generation of the hash will now be outside the application, so the admin can generate it as the see fit.
