### ISSUE TITLE
Save the sha256 hash in the .ini instead of the plaintext password

### ISSUE THREAD

**Issue by tillhanke** [kenfallon/fix-ssh-on-pi#8]
It might be a good idea to add an option to save the SHA256 hash instead of the plaintext password within the .ini file. This way the security of the script would be improved.

**Comment by simmonmt** [comment]
FWIW I made this change and a bunch of others (terseness, some cleanup, some just because) in https://github.com/simmonmt/fix-ssh-on-pi. You're welcome to copy them (or not).

**Comment by kenfallon** [comment]
I am (finally) getting to this. I'm removing the option to have clear text passwords. The hash will be stored in the ini file
